### ISSUE TITLE
HACKTOBERFEST 2019 

### ISSUE THREAD

**Issue by ItaloSa** [bsi-developers/comunidade#10]
### Olá pessoal, gostaria de anunciar que estamos participando do **[Hacktoberfest 2019](https://hacktoberfest.digitalocean.com)**! 

Que tal contribuir com nossa comunidade e garantir mais um PR (Pull Request) pra poder ganhar sua **limited edition T-shirt**? Estamos com nossa [lista de contribuidores](https://github.com/bsi-developers/comunidade/blob/master/Contributors.md) aberta pra aceitar seu nome e seu perfil do github. Caso você não saiba como fazer um PR preparamos este [guia](https://github.com/bsi-developers/comunidade/blob/master/CONTRIBUTING.md) para você. Se você quiser contribuir mais com nossa comunidade, é só da uma olhadinha nas [issues](https://github.com/bsi-developers/comunidade/issues) abertas. Qualquer dúvida é só comentar. Let's hack!

**Comment by caiohsfar** [comment]
Bora bora boraaa
