### ISSUE TITLE
[Discussion] Precisamos de um site

### ISSUE THREAD

**Issue by ItaloSa** [bsi-developers/comunidade#5]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Acredito que precisamos de uma página web, uma landing page, pra poder ser uma forma mais amigável de mostrar nossa comunidade para o mundo. Uma ideia básica de conteúdo seria colocar lá todo conteúdo que a gente colocar no README do repositório. 

**Descreva as alternativas que você considerou**
Ainda não achei nada pra nos inspirar. Colocarei na discussão

**Contexto adicional**
Coloquem sugestões e ideias.

**Comment by jonathasbsouza** [comment]
Acredito que o ideal num primeiro momento é partir para um template básico pronto. Antes é necessário configurar o github pages e gerar um dominio no Freenom.

**Comment by ItaloSa** [comment]
Segui sua sugestão @jonathasbsouza e usei o github pages e o freenom. O repositório do site é [este aqui](https://github.com/bsi-developers/bsidevs.ml). Só não utilizei nenhum template, tentei fazer tudo o mais simples possível utilizando HTML, CSS e pouquíssimo JS. Acredito que com essa abordagem seja mais simples para as pessoas novas no desenvolvimento web.
